# Generated by Django 2.1.2 on 2019-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=5, verbose_name='이름')),
                ('birthday', models.IntegerField(verbose_name='생년월일')),
                ('group', models.CharField(max_length=10, verbose_name='직분')),
                ('parish', models.CharField(blank=True, max_length=10, verbose_name='교구')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(error_messages={'unique': '이미 가입된 아이디 입니다.'}, max_length=15, unique=True, verbose_name='ID')),
                ('tp', models.IntegerField(error_messages={'unique': '이미 가입된 연락처 입니다.'}, unique=True, verbose_name='연락처')),
                ('email', models.EmailField(error_messages={'unique': '이미 가입된 이메일 입니다.'}, max_length=255, unique=True, verbose_name='이메일')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
