# Generated by Django 2.1.2 on 2019-09-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190920_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(max_length=8, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tp',
            field=models.CharField(error_messages={'unique': '이미 가입된 연락처 입니다.'}, max_length=15, unique=True, verbose_name='연락처'),
        ),
    ]
