# Generated by Django 2.1.15 on 2019-12-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190920_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='uid',
        ),
    ]
