# Generated by Django 2.1.15 on 2020-01-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191228_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.CharField(choices=[(1, '주일학생'), (2, '중등부'), (3, '고등부'), (4, '청년'), (5, '성도'), (6, '평신도'), (7, '집사'), (8, '안수집사'), (9, '권사'), (10, '장로'), (11, '원로장로'), (12, '은퇴장로'), (13, '선교사'), (14, '전도사'), (15, '강도사'), (16, '목사'), (17, '원로목사'), (18, '담임목사')], max_length=10, verbose_name='직분'),
        ),
    ]
