# Generated by Django 2.1.15 on 2020-10-04 12:54

import ckeditor_uploader.fields
import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='한줄설명')),
                ('image', models.ImageField(upload_to=data.models.carousel_image_save, verbose_name='사진')),
                ('order', models.IntegerField(default=0, help_text='낮을수록 먼저나옵니다.', verbose_name='순서')),
            ],
            options={
                'verbose_name': '홈페이지 슬라이드',
                'verbose_name_plural': '홈페이지 슬라이드',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(blank=True, choices=[('501', '사랑부'), ('502', '영아부'), ('503', '유치부'), ('504', '유년부'), ('505', '초등부'), ('506', '중등부'), ('507', '고등부'), ('508', '청년1부'), ('509', '청년2부'), ('510', '청년3부')], max_length=10, verbose_name='구분')),
                ('image', models.ImageField(blank=True, upload_to=data.models.community_image_save, verbose_name='사진')),
                ('title', models.TextField(blank=True, verbose_name='표어')),
                ('goal', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='교육목표')),
                ('worship', models.TextField(blank=True, verbose_name='예배안내')),
                ('server', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='섬기는 사람들')),
                ('youtube', models.CharField(blank=True, default='', max_length=255, verbose_name='유튜브링크')),
            ],
            options={
                'verbose_name': '교육부서 관리',
                'verbose_name_plural': '교육부서 관리',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='일시')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '교회연혁 관리',
                'verbose_name_plural': '교회연혁 관리',
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='한줄설명')),
                ('image', models.ImageField(upload_to=data.models.popup_image_save, verbose_name='사진')),
            ],
            options={
                'verbose_name': '팝업 관리',
                'verbose_name_plural': '팝업 관리',
            },
        ),
    ]
