# Generated by Django 2.1.15 on 2020-01-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='일시')),
                ('content', models.CharField(max_length=255, verbose_name='내용')),
            ],
            options={
                'verbose_name': '교회연혁',
                'verbose_name_plural': '교회연혁 관리',
            },
        ),
    ]
