# Generated by Django 3.1.2 on 2020-10-18 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='end_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='종료일시'),
        ),
        migrations.AddField(
            model_name='popup',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작일시'),
        ),
    ]
