# Generated by Django 2.1.15 on 2020-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
    ]
