# Generated by Django 3.1.2 on 2020-10-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201018_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popup',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
