# Generated by Django 2.1.15 on 2020-01-18 17:38

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200116_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='한줄설명')),
                ('image', models.ImageField(upload_to=data.models.carousel_image_save, verbose_name='사진')),
            ],
            options={
                'verbose_name': '홈페이지 슬라이드',
                'verbose_name_plural': '홈페이지 슬라이드',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '섬기는 사람들',
                'verbose_name_plural': '섬기는 사람들',
            },
        ),
    ]
