# Generated by Django 3.1.2 on 2020-10-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201018_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='location',
            field=models.CharField(default='0/0', help_text='다른 팝업과 겹치지 않도록 유의하세요.', max_length=30, verbose_name='팝업창 위치'),
        ),
    ]
