# Generated by Django 3.1.2 on 2020-10-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_popup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='location',
            field=models.CharField(default='0/0', help_text='가로/세로(px)<br>다른 팝업과 겹치지 않도록 유의하세요.', max_length=30, verbose_name='팝업창 위치'),
        ),
    ]
