# Generated by Django 2.1.15 on 2020-01-18 23:40

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_carousel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='charge',
            field=models.CharField(blank=True, max_length=50, verbose_name='담당사역'),
        ),
        migrations.AddField(
            model_name='server',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='server',
            name='htp',
            field=models.CharField(blank=True, max_length=15, verbose_name='집전화'),
        ),
        migrations.AddField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, upload_to=data.models.server_image_save, verbose_name='사진'),
        ),
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=5, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='server',
            name='office',
            field=models.CharField(blank=True, choices=[('1', '주일학생'), ('2', '중등부'), ('3', '고등부'), ('4', '청년'), ('5', '성도'), ('6', '평신도'), ('7', '집사'), ('8', '안수집사'), ('9', '권사'), ('10', '장로'), ('11', '원로장로'), ('12', '은퇴장로'), ('13', '선교사'), ('14', '전도사'), ('15', '강도사'), ('16', '목사'), ('17', '원로목사'), ('18', '담임목사')], max_length=10, verbose_name='직분'),
        ),
        migrations.AddField(
            model_name='server',
            name='tp',
            field=models.CharField(blank=True, max_length=15, verbose_name='핸드폰'),
        ),
    ]
