# Generated by Django 2.1.15 on 2020-01-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200118_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='div',
            field=models.CharField(blank=True, choices=[('1', '부목사'), ('2', '협동목사'), ('3', '전임전도사'), ('4', '교육전도사'), ('5', '파송선교사'), ('6', '방송간사'), ('7', '사무간사'), ('8', '관리집사'), ('9', '시무장로'), ('10', '원로장로'), ('11', '은퇴장로'), ('12', '협동장로')], max_length=10, verbose_name='구분'),
        ),
    ]
