# Generated by Django 3.1.2 on 2020-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201019_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='직분')),
            ],
            options={
                'verbose_name': '직분 관리',
                'verbose_name_plural': '직분 관리',
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='교구')),
            ],
            options={
                'verbose_name': '교구 관리',
                'verbose_name_plural': '교구 관리',
            },
        ),
    ]
