# Generated by Django 2.1.15 on 2020-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_server_div'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastolIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(verbose_name='학력')),
                ('career', models.TextField(verbose_name='사역경력')),
                ('experience', models.TextField(verbose_name='활동경력')),
            ],
            options={
                'verbose_name': '담임목사소개 관리',
            },
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '교회연혁 관리', 'verbose_name_plural': '교회연혁 관리'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '섬기는 사람들 관리', 'verbose_name_plural': '섬기는 사람들 관리'},
        ),
        migrations.AlterField(
            model_name='server',
            name='htp',
            field=models.CharField(blank=True, help_text="'-' 를 제외한 숫자만 입력해주세요.", max_length=15, verbose_name='집전화'),
        ),
        migrations.AlterField(
            model_name='server',
            name='tp',
            field=models.CharField(blank=True, help_text="'-' 를 제외한 숫자만 입력해주세요.", max_length=15, verbose_name='핸드폰'),
        ),
    ]
