# Generated by Django 3.1.2 on 2020-10-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_duty_parish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='소속')),
            ],
            options={
                'verbose_name': '소속 관리',
                'verbose_name_plural': '소속 관리',
            },
        ),
        migrations.DeleteModel(
            name='Parish',
        ),
    ]
