# Generated by Django 3.1.2 on 2020-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20201020_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.TextField(default='', verbose_name='링크'),
        ),
    ]
