# Generated by Django 2.1.15 on 2020-01-20 19:58

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200120_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastolintro',
            options={'verbose_name': '담임목사소개 관리', 'verbose_name_plural': '담임목사소개 관리'},
        ),
        migrations.AddField(
            model_name='pastolintro',
            name='image',
            field=models.ImageField(blank=True, upload_to=data.models.pastol_image_save, verbose_name='사진'),
        ),
    ]
