# Generated by Django 3.1.2 on 2020-10-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_carousel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='link',
            field=models.TextField(blank=True, default='', verbose_name='링크'),
        ),
    ]
