# Generated by Django 2.1.15 on 2020-01-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200120_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastolIntro',
            new_name='Pastol',
        ),
    ]
