# Generated by Django 3.1.2 on 2020-12-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20201029_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='link',
            field=models.TextField(blank=True, default='', verbose_name='링크'),
        ),
    ]
