# Generated by Django 2.1.15 on 2020-01-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200120_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(choices=[('1', '주일예배'), ('2', '주일학교'), ('3', '월-금요일'), ('4', '수요일'), ('5', '금요일')], max_length=10, verbose_name='구분')),
                ('time', models.CharField(max_length=30, verbose_name='시간')),
                ('sort', models.CharField(max_length=30, verbose_name='예배')),
                ('location', models.CharField(max_length=30, verbose_name='장소')),
            ],
            options={
                'verbose_name': '예배안내 관리',
                'verbose_name_plural': '예배안내 관리',
            },
        ),
    ]
