# Generated by Django 3.1.2 on 2021-01-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_popup_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='div',
        ),
    ]
