# Generated by Django 2.1.15 on 2020-01-21 19:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_worship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worship',
            name='div',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='location',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='time',
        ),
        migrations.AddField(
            model_name='worship',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
