# Generated by Django 3.1.2 on 2021-01-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20201029_1244'),
        ('data', '0011_remove_community_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='div',
            field=models.ForeignKey(limit_choices_to={'mainmenu__name': '다음세대'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.submenu', verbose_name='교육부서'),
        ),
    ]
