# Generated by Django 2.1.15 on 2020-01-22 11:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200121_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(blank=True, choices=[('101', '인사말'), ('102', '교회연혁'), ('103', '우리의 비젼'), ('104', '담임목사소개'), ('105', '섬기는 사람들'), ('106', '찾아오시는 길'), ('207', '예배안내'), ('501', '영아부'), ('502', '유치부'), ('503', '유년부'), ('504', '초등부'), ('505', '중등부'), ('506', '고등부'), ('507', '사랑부'), ('508', '청년1부'), ('509', '청년2부'), ('510', '청년3부'), ('511', '어린이집'), ('701', '양육시스템')], max_length=10, verbose_name='구분')),
                ('content', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': '커뮤니티 관리',
                'verbose_name_plural': '커뮤니티 관리',
            },
        ),
    ]
