# Generated by Django 2.1.15 on 2020-01-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='content',
        ),
        migrations.AddField(
            model_name='community',
            name='goal',
            field=models.TextField(blank=True, verbose_name='교육목표'),
        ),
        migrations.AddField(
            model_name='community',
            name='server',
            field=models.TextField(blank=True, verbose_name='섬기는 사람들'),
        ),
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.TextField(blank=True, verbose_name='표어'),
        ),
        migrations.AddField(
            model_name='community',
            name='worship',
            field=models.TextField(blank=True, verbose_name='예배안내'),
        ),
        migrations.AlterField(
            model_name='community',
            name='div',
            field=models.CharField(blank=True, choices=[('501', '영아부'), ('502', '유치부'), ('503', '유년부'), ('504', '초등부'), ('505', '중등부'), ('506', '고등부'), ('507', '사랑부'), ('508', '청년1부'), ('509', '청년2부'), ('510', '청년3부'), ('511', '어린이집')], max_length=10, verbose_name='구분'),
        ),
    ]
