# Generated by Django 2.1.15 on 2020-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200122_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='사진'),
        ),
    ]
