# Generated by Django 2.1.15 on 2020-01-23 14:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20200122_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '인사말 관리',
                'verbose_name_plural': '인사말 관리',
            },
        ),
        migrations.AlterField(
            model_name='community',
            name='div',
            field=models.CharField(blank=True, choices=[('501', '영아부'), ('502', '유치부'), ('503', '유년부'), ('504', '초등부'), ('505', '중등부'), ('506', '고등부'), ('507', '사랑부'), ('508', '청년1부'), ('509', '청년2부'), ('510', '청년3부')], max_length=10, verbose_name='구분'),
        ),
    ]
