# Generated by Django 2.1.15 on 2020-02-11 16:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20200123_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='server',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='섬기는 사람들'),
        ),
    ]
