# Generated by Django 2.1.15 on 2020-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20200613_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='m_type',
            field=models.CharField(choices=[('fixed', '고정형'), ('piclist', '사진형'), ('list', '리스트형')], default='list', max_length=50, verbose_name='타입'),
        ),
    ]
