# Generated by Django 2.1.15 on 2020-06-14 14:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20200613_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='goal',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='교육목표'),
        ),
    ]
