# Generated by Django 2.1.15 on 2020-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20200614_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='유튜브링크'),
        ),
        migrations.AlterField(
            model_name='community',
            name='div',
            field=models.CharField(blank=True, choices=[('501', '사랑부'), ('502', '영아부'), ('503', '유치부'), ('504', '유년부'), ('505', '초등부'), ('506', '중등부'), ('507', '고등부'), ('508', '청년1부'), ('509', '청년2부'), ('510', '청년3부')], max_length=10, verbose_name='구분'),
        ),
    ]
