# Generated by Django 2.1.15 on 2020-07-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20200714_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': '교육부서 관리', 'verbose_name_plural': '교육부서 관리'},
        ),
    ]
