# Generated by Django 2.1.15 on 2020-07-31 17:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20200725_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='')),
            ],
            options={
                'verbose_name': '양육시스템 관리',
                'verbose_name_plural': '양육시스템 관리',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='')),
            ],
            options={
                'verbose_name': '우리의 비전 관리',
                'verbose_name_plural': '우리의 비전 관리',
            },
        ),
        migrations.CreateModel(
            name='Wayto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='')),
            ],
            options={
                'verbose_name': '찾아오시는 길 관리',
                'verbose_name_plural': '찾아오시는 길 관리',
            },
        ),
        migrations.RemoveField(
            model_name='pastol',
            name='career',
        ),
        migrations.RemoveField(
            model_name='pastol',
            name='education',
        ),
        migrations.RemoveField(
            model_name='pastol',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='pastol',
            name='image',
        ),
        migrations.RemoveField(
            model_name='server',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='server',
            name='div',
        ),
        migrations.RemoveField(
            model_name='server',
            name='email',
        ),
        migrations.RemoveField(
            model_name='server',
            name='htp',
        ),
        migrations.RemoveField(
            model_name='server',
            name='image',
        ),
        migrations.RemoveField(
            model_name='server',
            name='name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='office',
        ),
        migrations.RemoveField(
            model_name='server',
            name='tp',
        ),
        migrations.AddField(
            model_name='pastol',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='server',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='worship',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
