# Generated by Django 2.1.15 on 2020-07-31 17:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20200731_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='goal',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='교육목표'),
        ),
        migrations.AlterField(
            model_name='community',
            name='server',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='섬기는 사람들'),
        ),
        migrations.AlterField(
            model_name='nurture',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='pastol',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='server',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='vision',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='wayto',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='worship',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
