# Generated by Django 2.1.15 on 2020-08-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20200731_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='is_allowed_to_not_superuser',
            field=models.BooleanField(default=False, verbose_name='일반회원 작성가능여부'),
        ),
    ]
