# Generated by Django 2.1.15 on 2020-09-05 12:57

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_submenu_is_allowed_to_not_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='한줄설명')),
                ('image', models.ImageField(upload_to=data.models.popup_image_save, verbose_name='사진')),
            ],
            options={
                'verbose_name': '팝업 관리',
                'verbose_name_plural': '팝업 관리',
            },
        ),
    ]
