# Generated by Django 2.1.15 on 2020-09-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_popup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='is_allowed_to_not_superuser',
        ),
    ]
