# Generated by Django 2.1.15 on 2020-09-20 22:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_remove_submenu_is_allowed_to_not_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('menu', models.ForeignKey(limit_choices_to={'m_type': 'fixed'}, on_delete=django.db.models.deletion.CASCADE, to='data.Submenu')),
            ],
            options={
                'verbose_name': '고정형메뉴 관리',
                'verbose_name_plural': '고정형메뉴 관리',
            },
        ),
    ]
