# Generated by Django 2.1.15 on 2020-09-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_fixedmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedmenu',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Nurture',
        ),
        migrations.DeleteModel(
            name='Pastol',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='mainmenu',
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
        migrations.DeleteModel(
            name='Wayto',
        ),
        migrations.DeleteModel(
            name='Welcome',
        ),
        migrations.DeleteModel(
            name='Worship',
        ),
        migrations.DeleteModel(
            name='FixedMenu',
        ),
        migrations.DeleteModel(
            name='Mainmenu',
        ),
        migrations.DeleteModel(
            name='Submenu',
        ),
    ]
