# Generated by Django 2.1.15 on 2020-10-04 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='', max_length=5, verbose_name='이름')),
                ('is_active', models.BooleanField(default=False, verbose_name='승인')),
                ('is_staff', models.BooleanField(default=False, help_text='관리자페이지 접속권한', verbose_name='스태프')),
                ('is_superuser', models.BooleanField(default=False, help_text='최고등급의 관리자권한', verbose_name='관리자')),
                ('is_social', models.BooleanField(default=False, verbose_name='소셜로그인')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입날짜')),
                ('uid', models.CharField(error_messages={'unique': '이미 가입된 아이디 입니다.'}, max_length=50, unique=True, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'ordering': ('-date_joined',),
            },
        ),
        migrations.CreateModel(
            name='PermissionsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='그룹명')),
            ],
            options={
                'verbose_name': '그룹관리',
                'verbose_name_plural': '그룹관리',
            },
        ),
    ]
