# Generated by Django 2.1.15 on 2020-07-04 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=5, verbose_name='이름')),
                ('birthday', models.DateField(verbose_name='생년월일')),
                ('office', models.CharField(choices=[('1', '주일학생'), ('2', '중등부'), ('3', '고등부'), ('4', '청년'), ('5', '성도'), ('6', '평신도'), ('7', '집사'), ('8', '안수집사'), ('9', '권사'), ('10', '장로'), ('11', '원로장로'), ('12', '은퇴장로'), ('13', '선교사'), ('14', '전도사'), ('15', '강도사'), ('16', '목사'), ('17', '원로목사'), ('18', '담임목사')], max_length=10, verbose_name='직분')),
                ('parish', models.CharField(blank=True, max_length=10, verbose_name='교구')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('is_active', models.BooleanField(default=False, verbose_name='승인')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='관리자')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입날짜')),
                ('uid', models.CharField(error_messages={'unique': '이미 가입된 아이디 입니다.'}, max_length=15, unique=True, verbose_name='ID')),
                ('tp', models.CharField(error_messages={'unique': '이미 가입된 연락처 입니다.'}, max_length=15, unique=True, verbose_name='연락처')),
                ('email', models.EmailField(error_messages={'unique': '이미 가입된 이메일 입니다.'}, max_length=255, unique=True, verbose_name='이메일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'ordering': ('-date_joined',),
            },
        ),
    ]
