# Generated by Django 2.1.15 on 2020-07-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='office',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tp',
        ),
    ]
