# Generated by Django 3.1.2 on 2020-10-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_populate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 가입된 이메일 입니다.'}, help_text='◈ 회원정보를 찾을 때 필요합니다', max_length=254, unique=True, verbose_name='이메일'),
        ),
    ]
