# Generated by Django 3.1.2 on 2020-10-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20201020_2246'),
        ('member', '0003_auto_20201014_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.belong', verbose_name='소속'),
        ),
        migrations.AddField(
            model_name='user',
            name='duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.duty', verbose_name='교구'),
        ),
    ]
