# Generated by Django 2.1.15 on 2020-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20200714_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social',
            field=models.BooleanField(default=False, verbose_name='소셜로그인'),
        ),
    ]
