# Generated by Django 2.1.15 on 2020-08-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_submenu_is_allowed_to_not_superuser'),
        ('member', '0004_user_is_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_permission',
            field=models.ManyToManyField(blank=True, related_name='user', to='data.Submenu'),
        ),
    ]
