# Generated by Django 3.1.2 on 2020-10-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_user_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tp',
            field=models.CharField(error_messages={'unique': '이미 가입된 연락처입니다.'}, help_text="'-'를 제외하고 입력해주세요.", max_length=15, null=True, unique=True, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 가입된 이메일입니다.'}, help_text='◈ 회원정보를 찾을 때 필요합니다', max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(error_messages={'unique': '이미 가입된 아이디입니다.'}, max_length=50, unique=True, verbose_name='ID'),
        ),
    ]
