# Generated by Django 2.1.15 on 2020-08-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_user_has_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_permission',
            field=models.ManyToManyField(blank=True, limit_choices_to={'m_type__contains': 'list'}, related_name='user', to='data.Submenu', verbose_name='게시판 권한'),
        ),
    ]
