# Generated by Django 2.1.15 on 2020-09-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_remove_submenu_is_allowed_to_not_superuser'),
        ('member', '0006_auto_20200821_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='그룹명')),
                ('write_permission', models.ManyToManyField(blank=True, limit_choices_to={'m_type__contains': 'list'}, related_name='group', to='data.Submenu', verbose_name='글 작성 권한')),
            ],
            options={
                'verbose_name': '그룹관리',
                'verbose_name_plural': '그룹관리',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_permission',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users', to='member.Group', verbose_name='그룹'),
        ),
    ]
