# Generated by Django 2.1.15 on 2020-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20200918_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='write_permission',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
