# Generated by Django 3.1.2 on 2021-02-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_community_div'),
        ('member', '0008_user_is_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.belong', verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='user',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.duty', verbose_name='직분'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tp',
            field=models.CharField(blank=True, error_messages={'unique': '이미 가입된 연락처입니다.'}, help_text="◈ ' - '를 제외하고 입력해주세요.", max_length=15, null=True, unique=True, verbose_name='연락처'),
        ),
    ]
