# Generated by Django 2.1.15 on 2020-09-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20200918_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='그룹명')),
            ],
            options={
                'verbose_name': '그룹관리',
                'verbose_name_plural': '그룹관리',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='관리자페이지 접속권한', verbose_name='스태프'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='최고등급의 관리자권한', verbose_name='관리자'),
        ),
    ]
