# Generated by Django 3.1.2 on 2020-12-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newyeareveword',
            options={'verbose_name': '송구영신예배 말씀뽑기', 'verbose_name_plural': '송구영신예배 말씀뽑기'},
        ),
        migrations.AlterField(
            model_name='newyeareveword',
            name='parish',
            field=models.CharField(choices=[('1', '1교구'), ('2', '2교구'), ('3', '3교구'), ('4', '1청년부'), ('5', '2청년부'), ('6', '3청년부'), ('7', '주일학교'), ('8', '기타')], max_length=10, verbose_name='소속'),
        ),
    ]
