# Generated by Django 3.1.2 on 2020-12-29 18:28

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201229_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewYearSpirit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=5, verbose_name='이름')),
                ('parish', models.CharField(choices=[('1', '1교구'), ('2', '2교구'), ('3', '3교구'), ('4', '1청년부'), ('5', '2청년부'), ('6', '3청년부'), ('7', '주일학교'), ('8', '기타')], max_length=10, verbose_name='소속')),
                ('words', models.ImageField(upload_to=event.models.new_year_spirit_upload, verbose_name='말씀')),
            ],
            options={
                'verbose_name': '새해 새마음 세이레 말씀뽑기',
                'verbose_name_plural': '새해 새마음 세이레 말씀뽑기',
            },
        ),
    ]
