# Generated by Django 3.1.2 on 2020-12-30 14:44

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_newyearspirit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newyearspirit',
            name='words',
            field=models.ImageField(upload_to=event.models.new_year_spirit_upload, verbose_name='인증사진'),
        ),
    ]
