# Generated by Django 2.1.15 on 2020-09-25 20:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
            ],
            options={
                'verbose_name': '고정형메뉴 관리',
                'verbose_name_plural': '고정형메뉴 관리',
            },
        ),
        migrations.CreateModel(
            name='Mainmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('order', models.IntegerField(help_text='낮을수록 먼저 배치됩니다', unique=True, verbose_name='순서')),
            ],
            options={
                'verbose_name': '메인메뉴 관리',
                'verbose_name_plural': '메인메뉴 관리',
            },
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('order', models.IntegerField(help_text='낮을수록 먼저 배치됩니다', verbose_name='순서')),
                ('m_type', models.CharField(choices=[('fixed', '고정형(수정가능)'), ('piclist', '사진형'), ('list', '리스트형'), ('fixed_uneditable', '고정형(수정불가)')], default='list', max_length=50, verbose_name='타입')),
                ('mainmenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='menu.Mainmenu', verbose_name='메인메뉴')),
            ],
            options={
                'verbose_name': '서브메뉴 관리',
                'verbose_name_plural': '서브메뉴 관리',
            },
        ),
        migrations.AddField(
            model_name='fixedmenu',
            name='menu',
            field=models.ForeignKey(limit_choices_to={'m_type': 'fixed'}, on_delete=django.db.models.deletion.CASCADE, to='menu.Submenu'),
        ),
    ]
