# Generated by Django 3.1.2 on 2020-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='tag',
            field=models.ManyToManyField(to='board.Posttag', verbose_name='태그'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='using_tag',
            field=models.BooleanField(default=False, verbose_name='태그사용여부'),
        ),
    ]
