# Generated by Django 3.1.2 on 2020-10-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='is_allowed_to_all',
            field=models.BooleanField(default=False, verbose_name='전체작성가능'),
        ),
    ]
