# Generated by Django 3.1.2 on 2020-10-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201015_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='exposure_home',
            field=models.IntegerField(default=0, help_text='asd', verbose_name='홈 화면 노출 여부'),
        ),
    ]
