# Generated by Django 3.1.2 on 2020-10-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_submenu_exposure_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='exposure_home',
            field=models.IntegerField(default=0, help_text='<table><tbody><tr><td>1</td><td>2</td></tr><tr><td>3</td><td>4</td></tr></tbody></table>', verbose_name='홈 화면 노출 여부'),
        ),
    ]
