# Generated by Django 3.1.2 on 2020-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20201019_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='exposure_home',
            field=models.IntegerField(default=0, help_text="<table style='text-align:center;'><tbody><tr><td colspan='2'>최근게시물</td></tr><tr><td>1</td><td>2</td></tr></tbody></table>", verbose_name='홈 화면 노출 여부'),
        ),
    ]
