# Generated by Django 3.1.2 on 2021-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20201029_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='숨김메뉴'),
        ),
    ]
