# Generated by Django 2.1.2 on 2019-09-23 19:30

import board.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=10, verbose_name='분류')),
                ('upload_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('preacher', models.CharField(max_length=20, verbose_name='설교자')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('video', models.FileField(upload_to=board.models.post_video_save, verbose_name='동영상')),
                ('audio', models.FileField(upload_to=board.models.post_audio_save, verbose_name='오디오파일')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 관리',
            },
        ),
    ]
