# Generated by Django 2.1.15 on 2019-12-28 21:10

import board.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
            },
        ),
        migrations.CreateModel(
            name='FixedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(choices=[('101', '인사말'), ('102', '교회연혁'), ('103', '우리의 비젼'), ('104', '담임목사소개'), ('105', '섬기는 사람들'), ('106', '찾아오시는 길'), ('207', '예배안내'), ('501', '영아부'), ('502', '유치부'), ('503', '유년부'), ('504', '초등부'), ('505', '중등부'), ('506', '고등부'), ('507', '사랑부'), ('508', '청년1부'), ('509', '청년2부'), ('510', '청년3부'), ('511', '어린이집'), ('701', '양육시스템')], max_length=10, verbose_name='분류')),
                ('html', models.TextField(verbose_name='html')),
            ],
            options={
                'verbose_name': '고정 템플릿 관리',
                'verbose_name_plural': '고정 템플릿 관리',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(choices=[('201', '금주의 말씀'), ('202', '주일오후예배'), ('203', '수요예배'), ('204', '금요철야예배'), ('205', '새벽기도'), ('206', '부흥회'), ('301', '할렐루야 찬양대'), ('302', '호산나 찬양대'), ('303', '찬양, 간증 집회'), ('401', '공지사항'), ('402', '교회소식'), ('403', '교우소식'), ('404', '새가족소개'), ('405', '교회앨범'), ('406', '자유게시판'), ('407', '기도요청'), ('408', '행사동영상'), ('409', '큐티나눔방'), ('601', '선교위원회'), ('602', '국내선교'), ('603', '캄보디아'), ('604', '인도'), ('605', '일본'), ('606', '태국'), ('607', '필리핀'), ('608', '이집트'), ('609', '탄자니아'), ('610', '카메룬'), ('611', '남아공'), ('612', '러시아'), ('613', '볼리비아'), ('614', '파푸아뉴기니'), ('615', '헝가리'), ('616', '단기선교'), ('702', '새가족부 자료실'), ('703', '확신반 자료실'), ('801', '문서자료실'), ('802', '기타자료실'), ('803', '주보자료실')], max_length=10, verbose_name='분류')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='제목')),
                ('preacher', models.CharField(blank=True, max_length=20, verbose_name='설교자')),
                ('video', models.CharField(blank=True, max_length=255, verbose_name='동영상')),
                ('words', models.CharField(blank=True, max_length=50, verbose_name='오늘의 말씀')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('published', models.BooleanField(default=True, verbose_name='공개여부')),
                ('writer', models.ForeignKey(on_delete=models.SET(board.models.set_defautwriter_when_deleted), related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 관리',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=board.models.post_image_save, verbose_name='사진')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='board.Post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.Post', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
