# Generated by Django 2.1.15 on 2020-10-06 21:14

import board.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(choices=[('201', '금주의 말씀'), ('202', '주일오후예배'), ('203', '수요예배'), ('204', '금요철야예배'), ('205', '새벽기도'), ('206', '부흥회'), ('301', '할렐루야 찬양대'), ('302', '호산나 찬양대'), ('303', '찬양, 간증 집회'), ('401', '공지사항'), ('402', '교회소식'), ('403', '교우소식'), ('404', '새가족소개'), ('405', '교회앨범'), ('406', '자유게시판'), ('407', '기도요청'), ('408', '행사동영상'), ('409', '큐티나눔방'), ('601', '선교위원회'), ('602', '국내선교'), ('603', '아시아'), ('604', '아프리카'), ('605', '기타'), ('606', '단기선교'), ('702', '새가족부 자료실'), ('703', '확신반 자료실'), ('801', '문서자료실'), ('802', '기타자료실'), ('803', '주보자료실')], max_length=10, verbose_name='분류')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
                ('date', models.DateField(blank=True, help_text='설교, 찬양, 기도에만 작성하세요.', null=True, verbose_name='일시')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='제목')),
                ('preacher', models.CharField(blank=True, help_text='설교에만 작성하세요.', max_length=20, verbose_name='설교자')),
                ('video', models.CharField(blank=True, help_text='유튜브 주소를 입력하세요.', max_length=255, verbose_name='동영상')),
                ('words', models.CharField(blank=True, help_text='설교에만 작성하세요.', max_length=50, verbose_name='오늘의 말씀')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='내용')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('published', models.BooleanField(default=True, verbose_name='공개여부')),
                ('notice', models.BooleanField(default=False, verbose_name='공지사항')),
                ('image', models.TextField(blank=True, verbose_name='사진')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 관리',
            },
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=board.models.post_file_save, verbose_name='첨부파일')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='file', to='board.Post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
            },
        ),
        migrations.CreateModel(
            name='Posttag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='최대 10글자입니다.', max_length=10, verbose_name='태그')),
            ],
            options={
                'verbose_name': '게시글 태그',
                'verbose_name_plural': '게시글 태그',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='board.Posttag'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=models.SET(board.models.set_defautwriter_when_deleted), related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.Post', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
