# Generated by Django 2.1.2 on 2019-09-24 12:47

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FileField(upload_to='', verbose_name='테스트')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, upload_to=board.models.post_audio_save, verbose_name='오디오파일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preacher',
            field=models.CharField(blank=True, max_length=20, verbose_name='설교자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to=board.models.post_video_save, verbose_name='동영상'),
        ),
    ]
