# Generated by Django 2.1.15 on 2019-12-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='desc',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
    ]
