# Generated by Django 2.1.2 on 2019-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190924_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='post',
            name='div',
            field=models.CharField(choices=[('201', '금주의 말씀'), ('202', '주일오후예배'), ('203', '수요예배'), ('204', '금요철야예배'), ('205', '새벽기도'), ('206', '부흥회'), ('301', '할렐루야 찬양대'), ('302', '호산나 찬양대'), ('303', '찬양, 간증 집회'), ('401', '공지사항'), ('402', '교회소식'), ('403', '교우소식'), ('404', '새가족소개'), ('405', '교회앨범'), ('406', '자유게시판'), ('407', '기도요청'), ('408', '행사동영상'), ('409', '큐티나눔방'), ('702', '새가족부 자료실'), ('703', '확신반 자료실'), ('801', '문서자료실'), ('802', '기타자료실'), ('803', '주보자료실')], max_length=10, verbose_name='분류'),
        ),
    ]
