# Generated by Django 2.1.2 on 2019-10-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20191029_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_no', models.CharField(max_length=10, verbose_name='분류')),
                ('html', models.TextField(verbose_name='html')),
            ],
            options={
                'verbose_name': '고정 template 관리',
                'verbose_name_plural': '고정 template 관리',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(blank=True, max_length=10, verbose_name='작성자'),
        ),
    ]
