# Generated by Django 2.1.15 on 2020-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='설교일'),
            preserve_default=False,
        ),
    ]
