# Generated by Django 3.1.2 on 2020-10-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20201019_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='div',
        ),
    ]
