# Generated by Django 2.1.15 on 2020-01-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, help_text='설교, 찬양, 기도에만 작성하세요.', null=True, verbose_name='일시'),
        ),
    ]
