# Generated by Django 2.1.2 on 2019-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20191031_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedview',
            old_name='menu_no',
            new_name='div',
        ),
    ]
