# Generated by Django 3.1.2 on 2020-10-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_post_div'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='menu',
            new_name='div',
        ),
    ]
