# Generated by Django 2.1.2 on 2019-11-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20191101_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedview',
            options={'verbose_name': '고정 템플릿 관리', 'verbose_name_plural': '고정 템플릿 관리'},
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, verbose_name='공개여부'),
        ),
        migrations.AlterField(
            model_name='fixedview',
            name='div',
            field=models.CharField(choices=[('101', '인사말'), ('102', '교회연혁'), ('103', '우리의 비젼'), ('104', '담임목사소개'), ('105', '섬기는 사람들'), ('106', '찾아오시는 길'), ('207', '예배안내'), ('501', '영아부'), ('502', '유치부'), ('503', '유년부'), ('504', '초등부'), ('505', '중등부'), ('506', '고등부'), ('507', '사랑부'), ('508', '청년1부'), ('509', '청년2부'), ('510', '청년3부'), ('511', '어린이집'), ('701', '양육시스템')], max_length=10, verbose_name='분류'),
        ),
    ]
