# Generated by Django 2.1.15 on 2020-01-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200118_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixedView',
        ),
    ]
