# Generated by Django 3.1.2 on 2020-12-23 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20201218_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='reservation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='예약일시'),
        ),
    ]
