# Generated by Django 2.1.2 on 2019-11-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20191101_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload_data',
            new_name='upload_date',
        ),
    ]
