# Generated by Django 3.1.2 on 2020-12-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_post_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reservation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='예약일시'),
        ),
    ]
