# Generated by Django 2.1.2 on 2019-11-19 10:51

import board.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=board.models.post_image_save, verbose_name='사진')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='board.Post')),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진',
            },
        ),
    ]
