# Generated by Django 2.1.15 on 2020-02-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20200204_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preacher',
            field=models.CharField(blank=True, help_text='설교에만 작성하세요.', max_length=20, verbose_name='설교자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, help_text='유튜브 주소를 입력하세요.', max_length=255, verbose_name='동영상'),
        ),
        migrations.AlterField(
            model_name='post',
            name='words',
            field=models.CharField(blank=True, help_text='설교에만 작성하세요.', max_length=50, verbose_name='오늘의 말씀'),
        ),
    ]
