# Generated by Django 3.1.2 on 2020-12-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reservation',
            field=models.DateTimeField(verbose_name='예약일시'),
        ),
    ]
