# Generated by Django 2.1.15 on 2020-02-25 13:47

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20200211_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(blank=True, upload_to=board.models.post_file_save, verbose_name='첨부파일'),
        ),
    ]
