# Generated by Django 2.1.2 on 2019-12-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='words',
            field=models.CharField(blank=True, max_length=50, verbose_name='오늘의 말씀'),
        ),
    ]
