# Generated by Django 2.1.15 on 2020-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20200225_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notice',
            field=models.BooleanField(default=False, verbose_name='공지사항'),
        ),
    ]
