# Generated by Django 2.1.15 on 2020-08-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_post_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posttag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='최대 10글자입니다.', max_length=10, verbose_name='태그')),
            ],
            options={
                'verbose_name': '게시글 태그',
                'verbose_name_plural': '게시글 태그',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='board.Posttag'),
        ),
    ]
