# Generated by Django 2.1.15 on 2019-12-28 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20191228_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(default='관리자', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
