# Generated by Django 2.1.15 on 2020-08-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20200818_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일'),
        ),
    ]
