# Generated by Django 2.1.15 on 2019-12-28 18:35

import board.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_auto_20191228_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=models.SET(board.models.set_defautwriter_when_deleted), related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
